# Global NuGet package security configuration
# This file helps maintain secure dependencies across all projects

# Security policy
security:
  # Enable security auditing
  audit: true
  
  # Vulnerability sources
  sources:
    - name: "NuGet Security Advisory"
      url: "https://api.nuget.org/v3-flatcontainer"
    
  # Package allowlist - Only allow trusted packages
  allowlist:
    # Microsoft packages
    - "Microsoft.*"
    
    # .NET Foundation packages
    - "System.*"
    - "AspNetCore.*"
    - "EntityFramework.*"
    
    # Testing packages
    - "xunit*"
    - "FluentAssertions"
    - "Moq"
    - "AutoFixture"
    
    # Documentation packages
    - "Swashbuckle.*"
    
    # Logging packages
    - "Serilog*"
    - "NLog*"
    
    # Popular utilities
    - "Newtonsoft.Json"
    - "AutoMapper"
    - "MediatR"
    
    # Redis
    - "StackExchange.Redis"
    
    # Kafka
    - "Confluent.Kafka"
    
    # Database
    - "Npgsql*"
    
  # Vulnerability severity thresholds
  severity_threshold: "low"
  
  # Auto-update security patches
  auto_update: true
  
  # Notifications
  notify_on_vulnerability: true
  
# Dependency update policy
updates:
  # Update schedule
  schedule: "weekly"
  
  # Auto-merge policy
  auto_merge:
    - type: "security"
      severity: ["critical", "high"]
    - type: "patch"
      confidence: "high"
      
  # Version constraints
  version_strategy: "increase_if_necessary"
  
# Package verification
verification:
  # Verify package signatures
  verify_signatures: true
  
  # Check package integrity
  verify_checksums: true
  
  # Scan for malware
  malware_scan: true

# Reporting
reporting:
  # Generate security reports
  security_report: true
  
  # License compliance
  license_check: true
  
  # Outdated packages report
  outdated_report: true
  
  # Format options
  formats: ["json", "xml", "html"]
  
  # Output directory
  output_dir: "./security-reports"

# Enterprise features
enterprise:
  # SBOM generation
  generate_sbom: true
  
  # Supply chain security
  supply_chain_verification: true
  
  # Compliance frameworks
  compliance:
    - "SOC2"
    - "PCI-DSS"
    - "OWASP"
    
  # Audit trail
  audit_trail: true
  
  # Risk assessment
  risk_assessment: true
